name: OculaCare
description: "Final Year Project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #navigation
  go_router: ^10.1.2

  #security
  flutter_dotenv: ^5.1.0

  #networking
  dio: ^5.4.1
  http: ^1.2.1

  #state management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5

  #preferences
  shared_preferences: ^2.2.2

  #utils
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  toastification: ^1.2.1
  camera: ^0.10.5+9
  lottie: ^3.1.0
  google_mlkit_face_detection: ^0.10.1
  pinput: ^4.0.0
  image: ^4.1.7
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  flutter_file_dialog: ^3.0.2
  nb_utils: ^7.0.2
  flutter_pdfview: ^1.2.7
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  intl_phone_number_input: ^0.7.4
  carousel_slider: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/android_icon.png"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  adaptive_icon_background: "#F9FAFB"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/lotties/
    - assets/pdfs/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

