name: ocula_care
description: "Final Year Project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #navigation
  go_router: ^13.2.0

  #security
  flutter_dotenv: ^5.1.0

  #networking
  dio: ^5.4.1

  #state management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5

  #preferences
  shared_preferences: ^2.2.2

  #utils
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

